# This workflow will build a package using Gradle

name: Gradle Build

on:
  push:
    branches: ['*']
  pull_request:
    types: [opened, synchronize]
#  release:
#    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the triggering repository
      run: |
         env
         echo $GITHUB_REPOSITORY
         declare -A SUBMODULES=( \
            [jameica]=jameica \
            [datasource]=lib/datasource \
            [util]=lib/util \
            [example]=plugins/example \
            [hibiscus]=plugins/hibiscus \
            )

         REPONAME=${GITHUB_REPOSITORY#*/}
         if [ $REPONAME = "jmc" ]; then
            echo "Github Actions run started from this repository"
         else
            echo git checkout -C ${SUBMODULES[$REPONAME]} $GITHUB_REF
         fi
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Gradle
      run: chmod +x gradlew && ./gradlew build
